name: glue
description: Flutter Glue helper.
version: 1.0.0
author: amine.bizid@gmail.com


environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"

dependencies:
  rxdart: ">=0.18.1 <1.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter